### PR TITLE
WIP Refactor scapegoat inspections generator

### LINKED ISSUE #102: FastClasspathScanner is outdated -- consider porting to ClassGraph
Your project, `mwz/sonar-scala`, depends on the outdated library FastClasspathScanner in the following source files:

* [`project/ScapegoatInspectionsGenerator.scala`](https://github.com/mwz/sonar-scala/tree/master/project/ScapegoatInspectionsGenerator.scala)

FastClasspathScanner has been significantly reworked since the version your code depends upon:

* a significant number of bugs have been fixed
* some nontrivial API changes have been made to simplify and unify the API
* FastClasspathScanner has been renamed to ClassGraph: https://github.com/classgraph/classgraph

ClassGraph is a significantly more robust library than FastClasspathScanner, and is more future-proof. All future development work will be focused on ClassGraph, and FastClasspathScanner will see no future development.

Please consider porting your code over to the new ClassGraph API, particularly if your project is in production or has downstream dependencies:

* https://github.com/classgraph/classgraph/wiki/Porting-FastClasspathScanner-code-to-ClassGraph
* https://github.com/classgraph/classgraph/wiki/Code-examples
* https://github.com/classgraph/classgraph/wiki/ClassGraph-API

Feel free to close this bug report if this code is no longer in use. (You were sent this bug report because your project depends upon FastClasspathScanner, and has been starred by 25 users. Apologies if this bug report is not helpful.)

### PR DESCRIPTION
**Pull request by BalmungSan**
Fixes #102 

Peding:
- [X] Unit tests.
- [X] PR review feedback.
- [X] Sync with master if #108 gets merged first.

**Important notes:**
I put the ScapegoatInspections.scala file in the _resources_ directory becasue this import `org.sonar.api.batch.rule.Severity`, was making the compilation fail. And I don't really want to add a dependency in the **SonarQubeAPI** to the meta project.

I made everything in the scapegoat inspections file private to the scapegoat package, in favor of my idea of exposing a method in the `QualityProfiles` for creating the **Scapegoat+Scalastyle** quality profile. I'll work on that, after finishing with this.

### Edit
**PS:** I just noticed we have a difference for naming tests classes, I use `SomethingSpec` and you `SomethingTest`, we should stick to one for making the code more consice. I'm happy with any of them, so no problem if you want to change everything to Test.

### CODE REVIEW

File: project/src/main/scala/ScapegoatInspectionsGenerator.scala [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+    val transformed = fillTemplate(templateFile, stringifiedScapegoatIsnpections)
+
+    val scapegoatInspectionsFile = (sourceManaged in Compile).value / "scapegoat" / "inspections.scala"
+    IO.write(scapegoatInspectionsFile, transformed)
+
+    Seq(scapegoatInspectionsFile)
+  }
+
+  /** Returns all scapegoat inspections, except the ones that should be ignored */
+  def extractInspections(): List[(String, Inspection)] =
```
Comment (BalmungSan) [inline project/src/main/scala/ScapegoatInspectionsGenerator.scala]: Do you have any ideas for testing this method?

File: project/build.sbt [hunk 2]
```diff
@@ -3,7 +3,7 @@ libraryDependencies ++= Seq(
   "org.sonarsource.update-center" % "sonar-update-center-common" % "1.21.0.561",
   // Scapegoat & scalastyle inspections generator dependencies
   "com.sksamuel.scapegoat" %% "scalac-scapegoat-plugin" % "1.3.7",
-  "io.github.lukehutch" % "fast-classpath-scanner" % "3.1.13",
+  "io.github.classgraph" % "classgraph" % "4.1.6",
```
Comment (mwz) [inline project/build.sbt]: 👍

File: project/src/main/scala/ScalastyleInspectionsGenerator.scala [hunk 3]
```diff
@@ -57,7 +57,6 @@ object ScalastyleInspectionsGenerator {
         "scala",
         "ScalastyleInspections.scala"
       )
-      .toFile
```
Comment (mwz) [inline project/src/main/scala/ScalastyleInspectionsGenerator.scala]: Oh, I see that conversion to File was unnecessary 👍

File: project/src/main/scala/ScapegoatInspectionsGenerator.scala (hunk 1 above)
Comment (mwz) [reply project/src/main/scala/ScapegoatInspectionsGenerator.scala]: 🤔 I guess to test `ClassGraph` in isolation you would need to call this function and inspect the collection that you get back. IMHO it's probably not necessary since your other tests already cover this in a way (indirectly).

File: project/src/main/scala/ScapegoatInspectionsGenerator.scala [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+      }
+
+  /** Stringifies a list of scapegoat inspections */
+  def stringifyInspections(scapegoatInspections: List[(String, Inspection)]): List[String] =
+    scapegoatInspections map {
+      case (inspectionClassName, inspection) =>
+        s"""ScapegoatInspection(
+           |  id = "$inspectionClassName",
+           |  name = "${inspection.text}",
+           |  description = "${inspection.explanation.getOrElse("No Explanation")}",
```
Comment (mwz) [inline project/src/main/scala/ScapegoatInspectionsGenerator.scala]: I can't remember if I made a comment about this when you first implemented this, but maybe we should just leave the description blank (or just leave it as `None`) if it's missing instead of saying `No Explanation` - what do you think?

File: src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatInspectionsSpec.scala [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+package com.mwz.sonar.scala.scapegoat
+
+import org.scalatest.{FlatSpec, Inspectors, Matchers}
+import org.sonar.api.batch.rule.Severity
+
+/** Tests the generated scapegoat inspections file */
+class ScapegoatInspectionsSpec extends FlatSpec with Inspectors with Matchers {
+  "The Scapegoat Inspections object" should "define all scapegoat inspections" in {
+    ScapegoatInspections.AllInspections should have size 126
+    ScapegoatInspections.AllInspections.distinct should have size 126
```
Comment (mwz) [inline src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatInspectionsSpec.scala]: Is your concern here that the inspections might be duplicates because of our logic or what comes from Scapegoat?

**Comment by mwz** [comment]
> I put the ScapegoatInspections.scala file in the resources directory becasue this import org.sonar.api.batch.rule.Severity, was making the compilation fail. And I don't really want to add a dependency in the SonarQubeAPI to the meta project.

I've already added some extra dependencies to the meta project, so if we want to be consistent I guess I should also move my Scalastyle template to resources.

> I made everything in the scapegoat inspections file private to the scapegoat package, in favor of my idea of exposing a method in the QualityProfiles for creating the Scapegoat+Scalastyle quality profile. I'll work on that, after finishing with this.

Interested to see what you can come up with 😄 

> PS: I just noticed we have a difference for naming tests classes, I use SomethingSpec and you SomethingTest, we should stick to one for making the code more consice. I'm happy with any of them, so no problem if you want to change everything to Test.

You're right. I can see the convention is to call your tests specs, so let's stick to that.

File: project/src/main/scala/ScapegoatInspectionsGenerator.scala (hunk 4 above)
Comment (BalmungSan) [reply project/src/main/scala/ScapegoatInspectionsGenerator.scala]: Uhm, Well I can change the type of that field from `String` to `Option[String]`, and leave the resposability of handling missing descriptions to the **RulesRepository**, that makes sense.
But what do you think would be a good _default_ value?, I agree "No Explanation" was not a good one; it was intendeed as a temporary palce holder but I forgot to change it. I'm not a fan of leaving it empty.

File: src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatInspectionsSpec.scala (hunk 5 above)
Comment (BalmungSan) [reply src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatInspectionsSpec.scala]: To be honest, both. I just want to be sure each inspection is unique.

**Comment by BalmungSan** [comment]
> "I've already added some extra dependencies to the meta project, so if we want to be consistent I guess I should also move my Scalastyle template to resources."

I already tried it, but it didn't work lol. Basically beacuse you use the case classes that you define in the generator logic and in its tests.
If you want you can refactor that. Nevertheless, that implies making the code **"Stringly Typed"** _(like the mine)_.
So, both have their prons and cons, I'll leave you take the decision.

> "Interested to see what you can come up with"

When this and #108 get merged I will work on that, hope you like it 😄 

> "You're right. I can see the convention is to call your tests specs, so let's stick to that."

Ok, since that will be a massive renaming of classes, I think is better if we made that later in a separate PR :+1:

File: project/src/main/scala/ScapegoatInspectionsGenerator.scala (hunk 4 above)
Comment (mwz) [reply project/src/main/scala/ScapegoatInspectionsGenerator.scala]: > Uhm, Well I can change the type of that field from String to Option[String], and leave the resposability of handling missing descriptions to the RulesRepository, that makes sense.

👍 

> But what do you think would be a good default value?, I agree "No Explanation" was not a good one; it was intendeed as a temporary palce holder but I forgot to change it. I'm not a fan of leaving it empty.

TBH, I'd be tempted to just leave it empty. If scapegoat doesn't provide any description then there isn't much we can do here. I've opened another issue some time ago (#87) which is relevant to this, perhaps we should tackle this separately and for now leave the description empty if it's empty.

Comment (BalmungSan) [reply project/src/main/scala/ScapegoatInspectionsGenerator.scala]: Roger

**Comment by mwz** [comment]
This should be good to go

> I already tried it, but it didn't work lol. Basically beacuse you use the case classes that you define in the generator logic and in its tests.
> If you want you can refactor that. Nevertheless, that implies making the code "Stringly Typed" (like the mine).
> So, both have their prons and cons, I'll leave you take the decision.

Ok, I'll think about it :)

> When this and #108 get merged I will work on that, hope you like it 😄



> Ok, since that will be a massive renaming of classes, I think is better if we made that later in a separate PR 👍

Yeah, agreed.

Ok, I think this should be good to go after making a change to the description field.

**Comment by BalmungSan** [comment]
> "Ok, I think this should be good to go after making a change to the description field."

Yes, my idea is to push the final changes, wait for any review comment, and after that synchronize with master _(as #108 will be merged first)_, and then this will be ready for merge.

**Comment by mwz** [comment]
Cool, happy to merge once you resolve the conflict.

File: project/build.sbt (hunk 2 above)
Comment (lukehutch) [reply project/build.sbt]: You'll need to bump this version to classgraph/classgraph-4.1.7 if there's a chance you will be running in a modular (JPMS) classpath -- I just pushed out an important fix yesterday for this case.

Comment (BalmungSan) [reply project/build.sbt]: Hi @lukehutch, thanks for the ping, we'll make sure to bump it before the next release :+1:
