### PR TITLE
Make Scapegoat sensor work with absolute file paths in the Scapegoat report

### LINKED ISSUE #115: Make Scapegoat sensor work with absolute file paths in the report
I use sbt-sonar plugin to do sonarScan, but I got below errors;
```
[info] INFO: [scapegoat] Initializing the Scapegoat sensor.\n
[info] INFO: [scapegoat] Loading the scapegoat report file: \'target/scala-2.12/scapegoat-report/scapegoat.xml\'.
[info] INFO: [scapegoat] Successfully loaded the scapegoat report file.
[info] INFO: [scapegoat] Saving the scapegoat issues for file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/target/scala-2/12/routes/main/controllers/ReverseRoutes.scala'.
ERROR: [scapegoat] The file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/target/scala-2/12/routes/main/controllers/ReverseRoutes.scala' couldn't be found.
[info] INFO: [scapegoat] Saving the scapegoat issues for file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/model/Conference.scala'.
ERROR: [scapegoat] The file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/model/Conference.scala' couldn't be found.
[info] INFO: [scapegoat] Saving the scapegoat issues for file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/controllers/AsyncController.scala'.
ERROR: [scapegoat] The file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/controllers/AsyncController.scala' couldn't be found.
[info] INFO: [scapegoat] Saving the scapegoat issues for file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/utils/authUtil.scala'.
ERROR: [scapegoat] The file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/utils/authUtil.scala' couldn't be found.
[info] INFO: [scapegoat] Saving the scapegoat issues for file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/services/query/queryImp/ESQueries.scala'.
ERROR: [scapegoat] The file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/services/query/queryImp/ESQueries.scala' couldn't be found.
[info] INFO: [scapegoat] Saving the scapegoat issues for file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/utils/ConfUtil.scala'.
ERROR: [scapegoat] The file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/utils/ConfUtil.scala' couldn't be found.
[info] INFO: [scapegoat] Saving the scapegoat issues for file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/target/scala-2/12/routes/main/controllers/javascript/JavaScriptReverseRoutes.scala'.
ERROR: [scapegoat] The file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/target/scala-2/12/routes/main/controllers/javascript/JavaScriptReverseRoutes.scala' couldn't be found.
[info] INFO: [scapegoat] Saving the scapegoat issues for file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/target/scala-2/12/routes/main/router/Routes.scala'.
ERROR: [scapegoat] The file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/target/scala-2/12/routes/main/router/Routes.scala' couldn't be found.
[info] INFO: [scapegoat] Saving the scapegoat issues for file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/services/query/QueryAdapter.scala'.
ERROR: [scapegoat] The file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/services/query/QueryAdapter.scala' couldn't be found.
[info] INFO: [scapegoat] Saving the scapegoat issues for file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/model/QueryParseError.scala'.
ERROR: [scapegoat] The file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/model/QueryParseError.scala' couldn't be found.
[info] INFO: [scapegoat] Saving the scapegoat issues for file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/model/Series.scala'.
[info] INFO: [scapegoat] Saving the scapegoat issues for file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/model/Metrics.scala'.ERROR: [scapegoat] The file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/model/Series.scala' couldn't be found.

ERROR: [scapegoat] The file '/Users/halin2/Documents/workspace/CallAnalyzerWrapper/app/model/Metrics.scala' couldn't be found.
[info] INFO: Sensor Scapegoat Sensor [scala] (done) | time=20ms`
```
But all files existed.
I saw a familiar issue #98 , it is closed because sonar-scala didn't support SonarQube 7.x.
But I don't think it is related to SonarQube 7.x, because I used SonarQube 6.7.5.

Could someone help me to fix this issue?

### PR DESCRIPTION
**Pull request by mwz**
I'm missing some unit tests with absolute file paths in the test Scapegoat reports, but I'll add those later if you're happy with this fix @BalmungSan.

@samlin425 you might also be interested in having a look at this.

Fixes #115.

### CODE REVIEW

File: src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParserSpec.scala [hunk 1]
```diff
@@ -16,25 +16,33 @@
...
-  it should "replace all dots (.) except the last one in a scaegoat path with slashes (/)" in {
+  it should "replace all dots (.) with slashes (/) in a scapegoat path except for the file extension" in {
     val scapegoatPath = "com.mwz.sonar.scala.scapegoat.TestFile.scala"
     val linuxPath = scapegoatReportParser.replaceAllDotsButLastWithSlashes(scapegoatPath)
 
     linuxPath shouldBe "com/mwz/sonar/scala/scapegoat/TestFile.scala"
   }
 
+  it should "replace all dots (.) with slashes (/) in a scapegoat absolute path except for the file extension" in {
+    val scapegoatPath = cwd.resolve("ScapegoatReportParserSpec.scala").toString.replace("/", ".")
```
Comment (BalmungSan) [inline src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParserSpec.scala]: I would rather use a literal value. Both for the input and for the expected result.

File: src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParserSpec.scala [hunk 2]
```diff
@@ -16,25 +16,33 @@
...
+    val linuxPath = scapegoatReportParser.replaceAllDotsButLastWithSlashes(scapegoatPath)
+
+    linuxPath shouldBe cwd.resolve("ScapegoatReportParserSpec.scala").toString
+  }
+
```
Comment (BalmungSan) [inline src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParserSpec.scala]: I would also add a test with filenames that have dots _(.)_ inside them. Like: `target/scala.12/.file.Scala`.

File: src/main/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParser.scala [hunk 3]
```diff
@@ -32,9 +32,21 @@ trait ScapegoatReportParserAPI {
...
   private[this] val AllDotsButLastRegex = raw"\.(?=.*\.)".r
 
-  /** Replaces all dots (.) except the last one in a scapegoat path with slashes (/) */
+  /**
+   * Replaces all dots '.' except the last one in a scapegoat path with slashes '/'
+   * while keeping valid directories which contain '.' in their name.
+   */
   private[scapegoat] def replaceAllDotsButLastWithSlashes(path: String): String =
-    AllDotsButLastRegex.replaceAllIn(target = path, replacement = "/")
+    if (path.startsWith(".")) {
```
Comment (BalmungSan) [inline src/main/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParser.scala]: I can't confirm it, neither test it _(cause I'm on my cell phone right now)_.  
But, I think this isn't working the way you think.
For example, I think this file will make it fail: `target.scala.12..file.Scala`

Comment (mwz) [reply src/main/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParser.scala]: I'll add some tests with extra dots in the middle of the path, but I think it's rather uncommon to have Scala source files hidden, i.e. starting with a `.`, so I think we can safely ignore this case.

File: src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParserSpec.scala (hunk 1 above)
Comment (mwz) [reply src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParserSpec.scala]: I don't think this is possible because the new implementation tests for the existence of the path on the file system so the input and output are both dynamic values based on where this project is located in the file system.

Comment (BalmungSan) [reply src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParserSpec.scala]: Oh, yeah yeah my fault...

File: src/main/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParser.scala (hunk 3 above)
Comment (BalmungSan) [reply src/main/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParser.scala]: Hidden files probably don't, but what about paths like `scala-2.12` ?

Comment (mwz) [reply src/main/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParser.scala]: yeah, so your example would work since the implementation checks first if `scala-2` exists in the file system and if it doesn't instead of resolving `12` as a subdirectory it concatenates it with a `.` and the previous path before checking again for existence in the file system - I'll add a unit test to cover that.

**Comment by mwz** [comment]
I've pushed unit tests, @BalmungSan would you mind having another look?

File: src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParserSpec.scala [hunk 4]
```diff
@@ -19,30 +19,43 @@
...
   }
 
+  it should "handle correctly dots in the path" in withFile(cwd.resolve("example.file.scala")) { file =>
+    val scapegoatPath = file.toString.replace("/", ".")
+    val linuxPath = scapegoatReportParser.replaceAllDotsButLastWithSlashes(scapegoatPath)
+
+    linuxPath shouldBe file.toString
+  }
+
+  it should "handle correctly multiple dots in path" in withFile(cwd.resolve("example.file.scala")) { file =>
```
Comment (BalmungSan) [inline src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParserSpec.scala]: Aren't those two tests exactly the same?, or what am I missing?

Comment (mwz) [reply src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParserSpec.scala]: Sorry, it was meant to be a different test - I fixed it in 9c8fdba.

Comment (BalmungSan) [reply src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatReportParserSpec.scala]: :+1:

**Comment by samlin425** [comment]
👍
