### PR TITLE
Fix scapegoat errors

### LINKED ISSUE #21: Remove all scapegoat errors
see discussion in #19

### PR DESCRIPTION
**Pull request by BalmungSan**
This will fix #21

By the moment I had only fixed the following warnings

- **com.sksamuel.scapegoat.inspections.FinalModifierOnCaseClass** (_info_)
- **com.sksamuel.scapegoat.inspections.RedundantFinalModifierOnMethod** (_info_)

**_(Updated 21/02/2018)_**

- **com.sksamuel.scapegoat.inspections.naming.MethodNames** (_info_) 
- **com.sksamuel.scapegoat.inspections.nulls.NullAssignment** (_warning_)
- **com.sksamuel.scapegoat.inspections.nulls.NullParameter** (_warning_)

The idea of this PR is that @mwz can go reviewing the changes as i made them.

This PR should be merged when all error get fixed or until I won't be able to fix the remaining.

### CODE REVIEW

**Comment by BalmungSan** [comment]
Hey  @mwz 

I just finished fixing all scapegoat errors!
You should review the changes meticulously.

File: src/main/scala/com/buransky/plugins/scoverage/StatementCoverage.scala [hunk 1]
```diff
@@ -82,18 +82,22 @@ case class ProjectStatementCoverage(name: String, children: Iterable[NodeStateme
...
-  val statementCount = children.filter(_.isInstanceOf[FileStatementCoverage]).map(_.statementCount).sum
-  val coveredStatementsCount =
-    children.filter(_.isInstanceOf[FileStatementCoverage]).map(_.coveredStatementsCount).sum
+  private val childValues = children collect {
+    case fsc: FileStatementCoverage => (fsc.statementCount, fsc.coveredStatementsCount)
+  }
+  val (statementCount, coveredStatementsCount) = childValues.foldLeft((0, 0)) {
+    case ((accStmtCount, accCoveredStmtCount), (stmtCount, coveredStmtCount)) =>
+      (accStmtCount + stmtCount, accCoveredStmtCount + coveredStmtCount)
+  }
```
Comment (mwz) [inline src/main/scala/com/buransky/plugins/scoverage/StatementCoverage.scala]: 👍

File: src/main/scala/com/buransky/plugins/scoverage/util/PathUtil.scala [hunk 2]
```diff
@@ -28,9 +28,10 @@ import scala.Iterator
  * @author Rado Buransky
  */
 object PathUtil {
+  type PathSeq = Vector[String]
```
Comment (mwz) [inline src/main/scala/com/buransky/plugins/scoverage/util/PathUtil.scala]: Any particular reason for making this a `Vector` as opposed to keeping it as an abstract `Seq`?

File: src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleRepository.scala [hunk 3]
```diff
@@ -89,15 +89,16 @@ class ScalastyleRepository extends RulesDefinition {
   private def determineFreeRuleKey(clazz: String, repo: NewRepository): String = {
     @tailrec
     def getFreeRuleKey(key: String, count: Int, repo: NewRepository): String = {
-      val testee = if (count == 0) key else "$key_$count"
-      if (repo.rule(testee) == null) {
-        testee
+      val ruleKey = if (count == 0) key else s"${key}_${count}d"
```
Comment (mwz) [inline src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleRepository.scala]: A redundant `d` at the end of the string?

Comment (mwz) [reply src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleRepository.scala]: Also, how did it work before without the interpolation? 😮

File: src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala [hunk 4]
```diff
@@ -116,7 +119,5 @@ class ScalastyleSensor(
 
   // sonar claims to accept null or a non zero lines, however if it is passed
   // null it blows up at runtime complaining it was passed 0
-  private def sanitiseLineNum(maybeLine: Option[Int]) =
-    if ((maybeLine getOrElse 0) != 0) maybeLine.get
-    else 1
```
Comment (mwz) [inline src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala]: This was quite awful! 🤢

File: src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala [hunk 5]
```diff
@@ -116,7 +119,5 @@ class ScalastyleSensor(
...
+  private def sanitiseLineNum(maybeLine: Option[Int]) = maybeLine getOrElse 1
```
Comment (mwz) [inline src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala]: To avoid non-zero line numbers, should we go for something like this instead `maybeLine.filter(_ != 0).getOrElse(1)`?

File: src/main/scala/com/sagacify/sonar/scala/ScalaSensor.scala [hunk 6]
```diff
@@ -9,14 +9,14 @@ import scalariform.ScalaVersions
...
-
   private val ScalaVersionPropertyKey = "sonar.scala.version"
 
   override def execute(context: SensorContext): Unit = {
     val charset = context.fileSystem().encoding.toString
     val versionProperty = context.config().get(ScalaVersionPropertyKey)
     val version =
-      if (context.config().get(ScalaVersionPropertyKey).isPresent) versionProperty.get() else ScalaVersions.Scala_2_11.toString()
+      if (context.config().get(ScalaVersionPropertyKey).isPresent) versionProperty.get()
+      else ScalaVersions.Scala_2_11.toString()
```
Comment (mwz) [inline src/main/scala/com/sagacify/sonar/scala/ScalaSensor.scala]: Oh, `versionProperty ` is a Java's `Optional`... Maybe including https://github.com/scala/scala-java8-compat as a dependency would make our life a bit easier in the future when dealing with Scala <-> Java conversions?
With this library the above would become:
```scala
versionProperty.asScala.getOrElse(ScalaVersions.Scala_2_11.toString)
```

File: src/main/scala/org/sonar/plugins/scala/Scala.scala [hunk 7]
```diff
@@ -1,37 +0,0 @@
...
- *
- * This program is distributed in the hope that it will be useful,
- * but WITHOUT ANY WARRANTY; without even the implied warranty of
- * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
- * Lesser General Public License for more details.
- *
- * You should have received a copy of the GNU Lesser General Public License
- * along with this program; if not, write to the Free Software Foundation,
- * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
- */
```
Comment (mwz) [inline src/main/scala/org/sonar/plugins/scala/Scala.scala]: You might want to move this copyright to the other file.

**Comment by mwz** [comment]
Looks good otherwise - thanks for making the effort to address all of the issues flagged by scapegoat.
This project is far away from where I would like it to be in terms of code quality and coverage, but this is a good step in the right direction. 👍

File: src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleRepository.scala (hunk 3 above)
Comment (BalmungSan) [reply src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleRepository.scala]: Oh yeah, Jesus my dyslexia will kill me some day.:sweat:
And I supose that you never need the interpolation before

File: src/main/scala/com/sagacify/sonar/scala/ScalaSensor.scala (hunk 6 above)
Comment (BalmungSan) [reply src/main/scala/com/sagacify/sonar/scala/ScalaSensor.scala]: Oh I really don't know, this was just a scalafmt change, I didn't touch it.

**Comment by BalmungSan** [comment]
Yeah, tomorrow I will check with more detail all your comments and make the corrections you suggested me. :+1:

File: src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala (hunk 5 above)
Comment (BalmungSan) [reply src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala]: If I get it right, sometimes the value will be a Some(0), and in those cases we should return 1 too ?
Is that even possible ?

File: src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala [hunk 8]
```diff
@@ -82,6 +83,8 @@ class ScalastyleSensor(
     log.debug("Matched to sonar rule " + rule)
 
     if (issuable.isDefined) {
+      // Here the use of the 'get' method is safe,
+      // because the option was checked to be defined.
```
[the remark this answers is not in the document]
Comment (BalmungSan) [reply src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala]: oh, what an elegant solution!!, I didn't knew it.

File: src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala (hunk 5 above)
Comment (BalmungSan) [reply src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala]: I'm thinking in something like this:

```scala
private def sanitiseLineNum(maybeLine: Option[Int]): Int = maybeLine match {
    case Some(0) => 1
    case Some(n) => n
    case None     => 1
}
```

Maybe  create a Constant, instead of using a plain literal.
Also, a negative line number doesn't make any sense  too... so maybe this will be better

```scala
private final val DefaultLineNumber = 1
/** Ensures that a line number is valid, if not returns a default value */
private def sanitiseLineNum(maybeLine: Option[Int]): Int = maybeLine match {
    case Some(linenum) if linenum > 0 => linenum
    case _  => DefaultLineNumber
}
```

File: src/main/scala/org/sonar/plugins/scala/Scala.scala (hunk 7 above)
Comment (BalmungSan) [reply src/main/scala/org/sonar/plugins/scala/Scala.scala]: Roger

**Comment by BalmungSan** [comment]
Hey @mwz,

All good now, except for the `sanitiseLineNum` method, please see my comment above, when you decide which implementation is better I will push the final commit with that change and the branch will be ready for merge.

File: src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala (hunk 5 above)
Comment (mwz) [reply src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala]: So essentially the following is a concise version of what we're trying to do:
```scala
maybeLine.filter(_ >= 0).getOrElse(1)
```

File: src/main/scala/com/sagacify/sonar/scala/ScalaSensor.scala (hunk 6 above)
Comment (mwz) [reply src/main/scala/com/sagacify/sonar/scala/ScalaSensor.scala]: I raised a new issue to address this - https://github.com/mwz/sonar-scala/issues/24.

File: src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala (hunk 5 above)
Comment (BalmungSan) [reply src/main/scala/com/ncredinburgh/sonar/scalastyle/ScalastyleSensor.scala]: oh yes, I will push it right now

**Comment by BalmungSan** [comment]
@mwz I think now we are ready to merge this.

File: src/main/scala/com/buransky/plugins/scoverage/util/PathUtil.scala (hunk 2 above)
Comment (mwz) [reply src/main/scala/com/buransky/plugins/scoverage/util/PathUtil.scala]: Ok, that's a fair point.

**Comment by mwz** [comment]
Yes, all looks good - thanks again for all of those changes.
