### PR TITLE
Fix for Scapegoat sensor not respecting module path for multi module projects.

### LINKED ISSUE #92: The new built-in scapegoat sensor cannot work.
I have try to use the `sonar-scala v6.5.0` with `sbt-sonar v1.3.0` in a two module project.   

config is
```scala
lazy val sonarSettings = Seq(
  sonarProperties ++= Map(
    "sonar.modules" -> "m1,m2",
    "sonar.scoverage.reportPath" -> "target/scala-2.11/scoverage-report/scoverage.xml",
    "sonar.scala.scapegoat.reportPath" -> "target/scala-2.11/scapegoat-report/scapegoat.xml",
    "sonar.scala.version" -> "2.11.0"
  )
)

lazy val root =
  (project in file(".") withId "root")
    .aggregate(m1, m2)
    .settings(name := "root")
    .settings(skip in publish := true)
    .settings(sonarSettings)
    .settings(aggregate in sonarScan := false)
```  

sadly, it raise an error in sonarScan
`ERROR: [scapegoat] Aborting the scapegoat sensor execution, cause: an error occurred while reading the scapegoat report file: 'target/scala-2.11/scapegoat-report/scapegoat.xml', the error was: target/scala-2.11/scapegoat-report/scapegoat.xml (No such file or directory).`

Use sonar-scanner from command line result in same error.   

Then I have a try of `v6.4.0` with `sonar-scala-extra v1.3.0` with same config. It works well.

I also tried to set `m1.sonar.scala.scapegoat.reportPath` and `m2.sonar.scala.scapegoat.reportPath` in config but it doesn't work.

### PR DESCRIPTION
**Pull request by mwz**
This PR fixes the Scapegoat sensor issue with multi-module projects where the report from the root module was used for each submodule. The fix was to resolve each report path relative to the working directory including the module directory when the sensor gets executed.

This fixes #92.

Hi @BalmungSan 👋, would you be able to review this PR?

### CODE REVIEW

File: src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatSensorSpec.scala [hunk 1]
```diff
@@ -363,6 +379,62 @@ class ScapegoatSensorSpec
     // validate the sensor behavior
     sensorContext.allIssues shouldBe empty
   }
+
+  it should "not report module issues" in {
```
Comment (BalmungSan) [inline src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatSensorSpec.scala]: I think that _'not'_ is out of place.

**Comment by BalmungSan** [comment]
Hi @mwz, Thanks a lot for fixing this, I have been incredibly busy, I'm sorry about that.

Everything looks fine to me _(except for that test name)_.

Just one thing, maybe we should bump some dependencies in this PR too, like sbt to 1.2.1, sbt-assembly to 0.14.7, etc...

:+1:

File: src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatSensorSpec.scala (hunk 1 above)
Comment (mwz) [reply src/test/scala/com/mwz/sonar/scala/scapegoat/ScapegoatSensorSpec.scala]: thanks for spotting this - fixed in 61a613a

**Comment by mwz** [comment]
Thanks for the review @BalmungSan. Since this is a hotfix, I'll just release it with the current versions and bump up dependencies and plugins in a separate PR.

**Comment by BalmungSan** [comment]
Ok, go ahead.
