### PR TITLE
Using semantic versioning scheme when parsing Scala version

### LINKED ISSUE #53: Use the semantic versioning scheme when parsing Scala version
Currently, the way the Scoverage sensor parses Scala version in `ScoverageSensorInternal.getDefaultScoverageReportPath`requires the major, minor, and the patch versions to be present and it will fail in cases where either the user doesn't specify a patch version or, for some reasons, the patch version includes more than one identifier (subversions), which is allowed by semver e.g. `2.12`, `2.12.0-alpha.1`, `1.0.0-0.3.7`, `1.0.0-x.7.z.92` etc.

We should parse the version so that only the major and minor versions are mandatory and the patch version is optional, e.g. `2.11`, `2.12` should be allowed.

### PR DESCRIPTION
**Pull request by BalmungSan**
Fixes #53

### CODE REVIEW

File: src/test/scala/com/mwz/sonar/scala/ScalaTest.scala [hunk 1]
```diff
@@ -8,15 +8,15 @@ import org.sonar.api.config.internal.MapSettings
...
       .asConfig()
 
-    Scala.getScalaVersion(conf) shouldBe "123"
+    Scala.getScalaVersion(conf).toString shouldBe "2.11.11"
   }
 
   it should "return the default value if not set" in {
     val conf = new MapSettings().asConfig()
-    Scala.getScalaVersion(conf) shouldBe "2.11.0"
+    Scala.getScalaVersion(conf).toString shouldBe "2.11.0"
```
[the remark this answers is not in the document]
Comment (BalmungSan) [reply src/test/scala/com/mwz/sonar/scala/ScalaTest.scala]: You're right, I'll add them tomorrow.

File: src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala [hunk 2]
```diff
@@ -46,16 +46,20 @@ object Scala {
...
   private val SourcesPropertyKey = "sonar.sources"
   private val DefaultSourcesFolder = "src/main/scala"
 
-  def getScalaVersion(settings: Configuration): String =
-    settings.get(ScalaVersionPropertyKey).toOption.getOrElse(DefaultScalaVersion)
+  def getScalaVersion(settings: Configuration): ScalaVersion =
+    settings
+      .get(ScalaVersionPropertyKey)
+      .toOption
+      .flatMap(ScalaVersion.parse)
```
[the remark this answers is not in the document]
Comment (BalmungSan) [reply src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala]: It will be valid if you write it like `2.12.` _(note the trailing dot)_

File: src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala [hunk 3]
```diff
@@ -46,16 +46,20 @@ object Scala {
...
+      .getOrElse(DefaultScalaVersion)
```
Comment (mwz) [inline src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala]: It might also be worth to distinguish a missing version from an incorrect/unsupported version with the latter possibly returning an error and terminating the analysis, but I'll leave it to you to decide whether this should be a part of this PR :+1:

Comment (BalmungSan) [reply src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala]: I don't know if it is possible to stop the analysis if the property is bad configured. well, here I'm talking about all the analysis process, not only the scoverage sensor.
Also I don't know if that would be better instead of just returning a default value.

In any case, in my opinion, it is outside the scope of this PR.

But what I consider worth would be to **log a _warning_** if the default version is returned. I don't know if you would like to add such logging statement inside the `getOrElse` method, or if you would prefer to separate the logging from the logic (like in `ScoverageSensor`).

File: src/test/scala/com/mwz/sonar/scala/ScalaTest.scala [hunk 4]
```diff
@@ -6,17 +6,49 @@ import org.scalatest.{FlatSpec, Matchers}
...
+
+  it should "be able to parse a version with an empty patch" in {
+    val conf = new MapSettings()
+      .setProperty("sonar.scala.version", "2.12.")
+      .asConfig()
+
+    Scala.getScalaVersion(conf).toString shouldBe "2.12."
+  }
+
+  it should "be able to parse a version without patch" in {
```
Comment (BalmungSan) [inline src/test/scala/com/mwz/sonar/scala/ScalaTest.scala]: So this is failing, but we want to make it pass.
The only idea I have is to use our own regex (to be precisely this one `"""(\d+)\.(\d+)(?:\.(.+))?""".r`). Do you like it? or what other ideas do you have?

```scala
scala> val r = """(\d+)\.(\d+)(?:\.(.+))?""".r
r: scala.util.matching.Regex = (\d+)\.(\d+)(?:\.(.+))?

scala> r.unapplySeq("2.12.6")
res6: Option[List[String]] = Some(List(2, 12, 6))

scala> r.unapplySeq("2.12")
res7: Option[List[String]] = Some(List(2, 12, null))
```

File: src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala (hunk 3 above)
Comment (mwz) [reply src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala]: Yes, adding a separate warning message would be definitely useful 👍

File: src/test/scala/com/mwz/sonar/scala/ScalaTest.scala (hunk 4 above)
Comment (mwz) [reply src/test/scala/com/mwz/sonar/scala/ScalaTest.scala]: Yeah, I think your regex is ok 👍 

You can also probably reuse the `parse` function from scaliform with a small change, e.g.:

```scala
import scalariform.ScalaVersion
import scalariform.utils.Utils._

val VersionPattern = """(\d+)\.(\d+)(?:\.(.+))?""".r

def parse(s: String): Option[ScalaVersion] = s match {
  case VersionPattern(major, minor, _) =>
    for {
      major <- major.toIntOpt
      minor <- minor.toIntOpt
    } yield ScalaVersion(major, minor)
  case _ ⇒
    None
}
```

But obviously whenever you want to use the string version, you will need to concatenate the major and monir versions yourself since the `ScalaVersion.toString` returns an extra `.` at the end.

**Comment by BalmungSan** [comment]
Hello @mwz, I'm sorry for taking so long in finishing this, but it should be ready now.
If you're happy with the latest changes go ahead a merge this. 👍

File: src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala [hunk 5]
```diff
@@ -46,16 +48,42 @@ object Scala {
...
+  private val logger = Loggers.get(classOf[Scala])
+
+  def getScalaVersion(settings: Configuration): ScalaVersion = {
+    def parseVersion(s: String): Option[ScalaVersion] = s match {
+      case ScalaVersionPattern(major, minor) =>
+        for {
+          major <- major.toIntOpt
+          minor <- minor.toIntOpt
+        } yield ScalaVersion(major, minor)
+      case _ ⇒
```
Comment (mwz) [inline src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala]: `=>`

Comment (BalmungSan) [reply src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala]: :dizzy_face: How? I'll fix it **ASAP**.

File: src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala [hunk 6]
```diff
@@ -46,16 +48,42 @@ object Scala {
...
+    }
+
+    val scalaVersion = settings
+      .get(ScalaVersionPropertyKey)
+      .toOption
+      .flatMap(parseVersion)
+      .getOrElse(DefaultScalaVersion)
+
+    // log a warning if using the default scala version
+    if (scalaVersion == DefaultScalaVersion)
```
Comment (mwz) [inline src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala]: In this case, you would probably still show this warning even if you set the version to `2.11.0` yourself, which is a correct version - you probably want to show this warning only when you get `None` as a result of parsing the version.

File: src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala [hunk 7]
```diff
@@ -46,16 +48,42 @@ object Scala {
...
+      logger.warn(
+        s"[sonar-scala] The '$ScalaVersionPropertyKey' is not properly set or is missing, using the default value: 's$DefaultScalaVersion'"
```
Comment (mwz) [inline src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala]: `'s$DefaultScalaVersion'` - the `s` at the beginning is redundant.

**Comment by mwz** [comment]
It looks good otherwise! 👍

File: src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala (hunk 6 above)
Comment (BalmungSan) [reply src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala]: Not really, if you set `sonar.scala.version=2.11.0`, this variable will be `ScalaVersion(2, 11)` _(because we're ignoring the patch)_. Thus it **will not be equals to** `ScalaVersion(2, 11, "0")`.
I check that before pushing :+1:

File: src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala (hunk 7 above)
Comment (BalmungSan) [reply src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala]: O god my dyslexia again. Sorry for that.

File: src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala (hunk 6 above)
Comment (mwz) [reply src/main/scala/com/mwz/sonar/scala/ScalaPlugin.scala]: Oh yes, you're right.

**Comment by BalmungSan** [comment]
Sorry for the delay 😞 
It should be ready now.

**Comment by mwz** [comment]
Great, thanks for the changes.
